### ISSUE TITLE
Error in Login API while sending data via front-end

### ISSUE THREAD

**Issue by GVishnudhasan** [GVishnudhasan/Performance-Appraisal#3]
The Login API is working perfectly while sending data via Postman to the backend.

The problem is that there are some type issues with the FacultyID and Password fields. I couldn't fix that issue.

`OPTIONS /v1/login 204 0.998 ms - 0
Error: Illegal arguments: undefined, string
    at _async (/Users/mymac/Desktop/Performance-Appraisal/DemoApp/backend/node_modules/bcryptjs/dist/bcrypt.js:286:46)
    at /Users/mymac/Desktop/Performance-Appraisal/DemoApp/backend/node_modules/bcryptjs/dist/bcrypt.js:307:17
    at new Promise (<anonymous>)
    at Object.bcrypt.compare (/Users/mymac/Desktop/Performance-Appraisal/DemoApp/backend/node_modules/bcryptjs/dist/bcrypt.js:306:20)
    at exports.login (/Users/mymac/Desktop/Performance-Appraisal/DemoApp/backend/controllers/mController.js:24:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
POST /v1/login 500 103.731 ms - 26`

**Comment by GVishnudhasan** [comment]
FIxed
